FROM apache/airflow:2.10.5-python3.11

USER root

COPY requirements-dbt.txt /tmp/requirements-dbt.txt
RUN python -m venv /opt/dbt-venv \
    && /opt/dbt-venv/bin/pip install --no-cache-dir -r /tmp/requirements-dbt.txt \
    && ln -s /opt/dbt-venv/bin/dbt /usr/local/bin/dbt

USER airflow
